Ht10 collections
dimacom/java-core-ht pull request #12
Opened 2021-03-29 15:38 UTC by dimacom

Task1-Task6

2021-04-05 13:15 UTC, du-java requested changes

2021-04-05 13:15 UTC, ghost commented on src/ht10Collections/Task2.java
> +        integers.removeIf(nextInteger -> nextInteger >= 10);
сможешь рассказать как этот метод работает?

2021-04-05 13:15 UTC, ghost commented on src/ht10Collections/Task5.java
> +            if(value.compareTo(person) == 0)counter++;
почему просто не сравнить имена через equal?

2021-04-05 13:15 UTC, ghost commented on src/ht10Collections/Task1.java
> +        Set<String> wordsSet = new TreeSet<>(Arrays.asList(wordsArray));
зачем TreeSet?

2021-04-05 13:15 UTC, du-java commented on src/ht10Collections/Task4.java
> +
`        Person person = new Person("test", "test", LocalDate.of(2020, 1, 1), 1);

        Map<Integer, Person> map = new HashMap<>();
        map.put(1, person);

        peopleBirthdayWithoutSeason(Season.AUTUMN, map);`
        
Если запустить так, то пишет что человек рожденный 1 января родился осенью

2021-04-05 13:15 UTC, du-java commented on src/ht10Collections/Task6.java
> +        people.values().removeIf(next -> next.getSalary() < 500);
сможешь рассказать про функциональные интерфейсы?

2021-04-05 18:21 UTC, dimacom commented on src/ht10Collections/Task2.java
> +        integers.removeIf(nextInteger -> nextInteger >= 10);
Да

2021-04-05 18:24 UTC, dimacom commented on src/ht10Collections/Task5.java
> +            if(value.compareTo(person) == 0)counter++;
Просто разбирался как работает compareTo() поэтому такая реализация.

2021-04-05 18:28 UTC, dimacom commented on src/ht10Collections/Task1.java
> +        Set<String> wordsSet = new TreeSet<>(Arrays.asList(wordsArray));
В задании с использованием Set, Treeset одна из реализаций Set, вроде подходит. Для разнообразия

2021-04-05 18:33 UTC, dimacom commented on src/ht10Collections/Task6.java
> +        people.values().removeIf(next -> next.getSalary() < 500);
Да, но не сильно глубоко. Принцип понимаю, использую не уверенно.

2021-04-05 18:48 UTC, dimacom commented on src/ht10Collections/Task4.java
> +
Да, все так. Пытался передать в названием метода то что он делает.
Метод выводит всех personov, кроме тех у кого день рождение в сезоне указанно в параметрах. Программа решает задачу учителя которая хочет поздравить всех учиников кроме тех у кого день рождение летом. Понимаю что можно было проще, хотел разобраться с Enum.

2021-04-06 15:26 UTC, du-java commented on src/ht10Collections/Task4.java
> +
ты проверяешь в стринге с помощью contains, но т.к. 9_10_11 содержат символ 1, то работает не корректно

2021-04-08 10:37 UTC, dimacom commented on src/ht10Collections/Task4.java
> +
исправил, но мне кажется немного топорно. наверное есть какой-то способ  проверить на содержание подстроки?

2021-04-17 18:54 UTC, du-java approved these changes

2021-04-19 04:36 UTC, merged