Ht10 collections part2
dimacom/java-core-ht pull request #13
Opened 2021-04-04 06:23 UTC by dimacom

2021-04-05 13:29 UTC, du-java requested changes

2021-04-05 13:29 UTC, du-java commented on src/ht10Collections/part2/Task10.java
> +        Set<Integer> numbers = new LinkedHashSet<>(Arrays.asList(1, 2, 3, 4, 5, 6));
если будет нечетное количество 1, 2, 3, 4, 5, 6, 7

2021-04-05 18:17 UTC, dimacom commented on src/ht10Collections/part2/Task10.java
> +        Set<Integer> numbers = new LinkedHashSet<>(Arrays.asList(1, 2, 3, 4, 5, 6));
> если будет нечетное количество 1, 2, 3, 4, 5, 6, 7

Решил этот вопрос добавлением 0 в конец списка на результат не влияет, список всегда состоит из честного количества элементов.

2021-04-05 18:19 UTC, dimacom commented on src/ht10Collections/part2/Task10.java
> +        Set<Integer> numbers = new LinkedHashSet<>(Arrays.asList(1, 2, 3, 4, 5, 6));
![Screenshot_20210405_211847.jpg](https://user-images.githubusercontent.com/74108547/113609509-2b1e0280-964c-11eb-84e9-c63dfcd453ed.jpg)

2021-04-06 15:23 UTC, du-java commented on src/ht10Collections/part2/Task10.java
> +        Set<Integer> numbers = new LinkedHashSet<>(Arrays.asList(1, 2, 3, 4, 5, 6));
[1, 2, 3, 4, 5, 6, 7]
[3, 7, 11]
[10, 11]
[21]
но что-то не работает

2021-04-08 10:26 UTC, dimacom commented on src/ht10Collections/part2/Task10.java
> +        Set<Integer> numbers = new LinkedHashSet<>(Arrays.asList(1, 2, 3, 4, 5, 6));
3+4 тоже 7 затирает это же Set по условию задачи

2021-04-17 18:57 UTC, du-java approved these changes

2021-04-19 04:36 UTC, merged